# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FieldConnect
                                 A QGIS plugin
 Connects to Field Desktop
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-18
        copyright            : (C) 2025 by VZG
        email                : oliver.zapiec@gbv.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FieldConnect class from file FieldConnect.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .field_connect import FieldConnect

    return FieldConnect(iface)
